$ANSIBLE_VAULT;1.1;AES256
64636239633939323939366261363634386166613037616362363062366338333961356564323361
3134373263323265356463623930616237633838346162620a393336303161393931623061643434
37333737353836613338653838613062383564366463343962393837663530383861613164393735
6464363332323966310a336435306565356333663736356563656465383964633937616233396364
63646661373634383738393739653663373933306537646438333435346261653561623435396436
37616564663635346662336335316530383261663164373131366164623362616637353739313437
32333039376361316663376261383833353931636263653239396133313735383937333865336564
36636564343263333764333937313537373730313834346463323332326233643739333338363838
32386133326636303932333032643437653437353631646261383435376639326238376561653061
39366235303038326330383636623932386237626435653435376231653862303761633838656563
35653762616362633334616162336238336139383437613663666633366137666230353037376130
37376132373434353735386234386438646535376562343236383433333531623261313261313631
38666531663436663037323632383637303437343635613964373932383634303233623235333239
65643933393364653630636661303337373863333838623135373137396432653734653264393834
63363361616434666332356234353036636662623632663461303265613166306535363764623263
63623239633765303233646532656465323061306436613235396630303161303737656637386632
62643362333434616362353661326632633335393732393734323264636563303163663731326431
61656537393137363938393964653434656136623338333234343135353466636362353734386334
39626463643365663231363363633135373361663632353835653261623365656562393664653664
37633739646335323339643265646462643163303333343837613538653166623666343866326331
66356538656365393563616164636433333534663935323466653132323939343738323364336661
35386435656431623439353661336462366263663238336265303831363964653339363263623232
64366239326536633666643734613838323463383031636264396531373032663237643763633062
32303735383032383230396439353334653736363130343938306266386532376432623433343233
30656138653863373238396461636538393233386361396233643132383563623434666461346438
35633931353462323161396433346137646661393636623230326565633063656462313034613531
64376537613432383931343163333661323837633239636461303939376236356434633462346464
39396438623831393665646562346463643837356439366632333363323263633933376561643537
3761
