metadata:
  namespace: cd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: git@github.com:Alite777/secure-container-images.git
    targetRevision: dev
  project: default
