metadata:
  namespace: cd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cd
  source:
    repoURL: git@github.com:Alite777/Secure_Container_Images.git
    targetRevision: dev
  project: default
