---
lab_all:
  children:
    # mgmt:
    #   hosts:
    #     jump01:
    #       ansible_host: 
    #     deployment:
    #       ansible_host: 
    k3s_servers:
      children:
        k3s_server:
          hosts:
            control_plane:
              ansible_host: aps_control-plane
              k3s_control_node: true
        k3s_agent:
          hosts:
            worker1:
              ansible_host: aps_worker1
              k3s_control_node: false
            worker2:
              ansible_host: aps_worker2
              k3s_control_node: false
      vars:
        ansible_user: root
        k3s_state: installed
            
          