# Helm installation (required for subsequent Helm tasks)
- name: Check if Helm is installed
  command: helm version --short
  register: helm_version_result
  changed_when: false
  failed_when: false

- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: helm_version_result.rc != 0

- name: Install Helm
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  when: helm_version_result.rc != 0